name: Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NORTHFLANK_API_KEY: your_northflank_api_key
  PROJECT_ID: your_project_id
  SERVICE_ID: your_service_id

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jernejofic444/mbajk-api .

      - name: Push Docker image to Docker Hub
        run: docker push jernejofic444/mbajk-api

      - name: Deploy to Northflank
        uses: northflank/deploy-to-northflank@v1
        with:
          northflank-api-key: ${{ secrets.NORTHFLANK_API_KEY }}
          project-id: mbajk-service
          service-id: mbajk-api
          image-path: https://hub.docker.com/r/jernejofic444/mbajk-api
