name: Fetch Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install  poetry 
          pip install dvc[s3]

      - name: DVC setup
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
          dvc pull -r origin

      - name: Install dependencies
        run: |
          poetry install --with dev --without win-dev

      - name: Run Tests
        run: |
          poetry run poe test-remote-api 

      - name: Fetch bike data
        run: |
          poetry run poe fetch-bike-data

      - name: Fetch weather data
        run: |
          poetry run poe fetch-weather-data

      - name: Commit and push data
        run: |
          dvc add data
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git pull
          git diff-index --quiet HEAD || (git commit -a -m "action: fetch latest data" --allow-empty)
          git push
          dvc push -r origin
          
    process:
      runs-on: ubuntu-latest
      needs: fetch

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Prerequisites
          run: |
            python -m pip install --upgrade pip
            pip install  poetry 
            pip install dvc[s3]

        - name: DVC setup
          run: |
            dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
            dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
            dvc pull -r origin

        - name: Install dependencies
          run: |
            poetry install --with dev --without win-dev

        - name: Run tests
          run: |
            poetry run poe test-remote-api

        - name: Process data
          run: |
            poetry run poe process

        - name: Commit and push data
          run: |
            dvc add data
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git pull
            git diff-index --quiet HEAD || (git commit -a -m "action: fetch latest data" --allow-empty)
            git push
            dvc push -r origin

      validation:
        runs-on: ubuntu-latest
        needs: process

        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: '3.12'

          - name: Prerequisites
            run: |
              python -m pip install --upgrade pip
              pip install  poetry 
              pip install dvc[s3]

          - name: DVC setup
            run: |
              dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
              dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
              dvc pull -r origin

          - name: Install dependencies
            run: |
              poetry install --with dev --without win-dev

          - name: Get reference data
            run: |
              dvc get . data/current_data.csv --rev $SHA_FETCH --out data/reference_data.csv --force

          - name: Run validation
            run: |
              poetry run poe validate

          - name: Commit and push data
            run: |
              dvc add data
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              git pull
              git diff-index --quiet HEAD || (git commit -a -m "action: fetch latest data" --allow-empty)
              git push
              dvc push -r origin
