name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install  poetry


    - name: Install dependencies
      run: |
        poetry install --with dev --without win-dev

    - name: Run tests
      run: |
        poetry run poe test
