name: Deploy Pipeline Service

on:
  push:
    branches:
      - main
    paths:
      - 'src/serve/**'
      - '.github/workflows/service-ci-cd.yml'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - 'src/serve/**'
      - '.github/workflows/service-ci-cd.yml'
      - 'Dockerfile'

env:
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  DATABASE_URI: sqlite:///predictions.sqlite


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install  poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --without win-dev

      #- name: Create SQLite Database
      #  run: |
      #    touch predictions.sqlite
      #    working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          poetry run poe test

      - name: Install Railway CLI
        run: bash <(curl -fsSL cli.new)

      - name: Retrieve Railway Secrets
        run: |
          export DAGSHUB_TOKEN=$(railway variable:get DAGSHUB_TOKEN)

      - name: Deploy to Railway
        run: railway up --service napovedna_storitev
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          DATABASE_URI: sqlite:///predictions.sqlite
          DAGSHUB_TOKEN: ${{ env.DAGSHUB_TOKEN }}